development:
  adapter: postgresql
  encoding: unicode
  database: WDI_Project_one_development
  # host: localhost
  pool: 5
  


test:
  adapter: postgresql
  encoding: unicode
  database: WDI_Project_one_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: WDI_Project_one_production
  pool: 5
